version: '3.8'
services:
  mlflow:
    image: python:3.13-slim
    command: sh -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns"
    volumes:
      - mlruns:/mlruns
    ports:
      - target: 5000
        published: 5000
        protocol: tcp

volumes:
  mlruns:
    driver: local
